/* config-nitrux.h. Generated by cmake from config-nitrux.h.cmake */

/*
 * SPDX-FileCopyrightText: 2014 Hugo Pereira Da Costa <hugo.pereira@free.fr>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#pragma once

/* Define to 1 if FrameworkIntegration/Kstyle libraries are found */
#cmakedefine01 NITRUX_HAVE_KSTYLE

