name: Nitrux KStyle Debian package

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      packageVersion:
        description: Package version
        required: true
        default: 6.80
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: debian:testing
      env:
        DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Install bootstrap packages
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends ca-certificates git sudo

      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: ./scripts/install-build-deps.sh

      - name: Build package
        run: ./scripts/build-deb.sh
        env:
          PACKAGE_VERSION: ${{ inputs.packageVersion }}

      - uses: actions/upload-artifact@v4
        with:
          name: nx-kstyle-theme-debian
          path: ./build/*.deb
